# Generated by Django 6.0.7 on 2026-08-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Utilities', 'Utilities'), ('Transport', 'Transport'), ('Salaries', 'Salaries'), ('Maintenance', 'Maintenance'), ('Supplies', 'Supplies'), ('Communication', 'Communication'), ('Banking', 'Banking'), ('Licences', 'Licences'), ('Marketing', 'Marketing'), ('Security', 'Security'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='expense',
            name='title',
            field=models.CharField(choices=[('Shop Rent', 'Shop Rent'), ('Electricity Bill', 'Electricity Bill'), ('Water Bill', 'Water Bill'), ('Internet Subscription', 'Internet Subscription'), ('Transport Expense', 'Transport Expense'), ('Fuel', 'Fuel'), ('Staff Salary', 'Staff Salary'), ('Casual Labour', 'Casual Labour'), ('Equipment Repair', 'Equipment Repair'), ('Computer Repair', 'Computer Repair'), ('Printer Repair', 'Printer Repair'), ('CCTV Maintenance', 'CCTV Maintenance'), ('Cleaning Supplies', 'Cleaning Supplies'), ('Office Supplies', 'Office Supplies'), ('Packaging Materials', 'Packaging Materials'), ('Stationery', 'Stationery'), ('Airtime', 'Airtime'), ('Bank Charges', 'Bank Charges'), ('M-Pesa Charges', 'M-Pesa Charges'), ('Business Permit', 'Business Permit'), ('Licences', 'Licences'), ('Security Services', 'Security Services'), ('Delivery Charges', 'Delivery Charges'), ('Advertising', 'Advertising'), ('Marketing', 'Marketing'), ('Refreshments', 'Refreshments'), ('Lunch Allowance', 'Lunch Allowance'), ('Equipment Purchase', 'Equipment Purchase'), ('Software Subscription', 'Software Subscription'), ('Miscellaneous Expense', 'Miscellaneous Expense')], max_length=200),
        ),
    ]
