# Generated by Django 6.0.7 on 2026-08-26 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_last_updated_inventory_reorder_level_and_more'),
        ('products', '0003_product_category_product_unit_alter_product_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='products.product'),
        ),
    ]
