# Generated by Django 6.0.7 on 2026-08-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='Hardware POS', max_length=200)),
                ('business_phone', models.CharField(blank=True, max_length=30)),
                ('business_email', models.EmailField(blank=True, max_length=254)),
                ('business_address', models.TextField(blank=True)),
                ('business_location', models.CharField(blank=True, max_length=200)),
                ('currency', models.CharField(default='KSh', max_length=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('low_stock_threshold', models.PositiveIntegerField(default=5)),
                ('receipt_footer', models.CharField(default='Thank you for shopping with us.', max_length=255)),
                ('show_business_phone', models.BooleanField(default=True)),
                ('show_business_address', models.BooleanField(default=True)),
                ('low_stock_notifications', models.BooleanField(default=True)),
                ('out_of_stock_notifications', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
