# Generated by Django 6.0.7 on 2026-08-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_total_amount_alter_sale_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='customer',
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('M-Pesa', 'M-Pesa')], default='Cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
