# Generated by Django 6.0.7 on 2026-08-28 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_category_product_unit_alter_product_barcode'),
        ('sales', '0003_remove_sale_customer_sale_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product'),
        ),
    ]
