# Generated by Django 6.0.7 on 2026-08-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Hardware', 'Hardware'), ('Timber', 'Timber'), ('Metals', 'Metals'), ('Furniture', 'Furniture'), ('Electrical', 'Electrical'), ('Plumbing', 'Plumbing'), ('Paint', 'Paint'), ('Other', 'Other')], default='Hardware', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('Piece', 'Piece'), ('Bag', 'Bag'), ('Box', 'Box'), ('Kg', 'Kg'), ('Metre', 'Metre'), ('Foot', 'Foot'), ('Litre', 'Litre'), ('Set', 'Set'), ('Pair', 'Pair'), ('Other', 'Other')], default='Piece', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
